// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentFlow.Persistance;

#nullable disable

namespace RentFlow.Persistance.Migrations
{
    [DbContext(typeof(RentFlowDbContext))]
    partial class RentFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentFlow.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanDeliver")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DeliveryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("RentFlow.Domain.Assets.AssetPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetPhotos");
                });

            modelBuilder.Entity("RentFlow.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SignatoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SignatoryId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RentFlow.Domain.Bookings.BookingRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingRole");
                });

            modelBuilder.Entity("RentFlow.Domain.Bookings.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PricingRules");
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RentFlow.Domain.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.Individual", b =>
                {
                    b.HasBaseType("RentFlow.Domain.Customers.Customer");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.IndividualEntrepreneur", b =>
                {
                    b.HasBaseType("RentFlow.Domain.Customers.Customer");

                    b.Property<string>("FactAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OGRNIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RepresentativeId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.Organization", b =>
                {
                    b.HasBaseType("RentFlow.Domain.Customers.Customer");

                    b.Property<string>("FactAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OGRN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Customers", t =>
                        {
                            t.Property("INN")
                                .HasColumnName("Organization_INN");

                            t.Property("RepresentativeId")
                                .HasColumnName("Organization_RepresentativeId");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("RentFlow.Domain.Assets.AssetPhoto", b =>
                {
                    b.HasOne("RentFlow.Domain.Assets.Asset", null)
                        .WithMany("Photos")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentFlow.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("RentFlow.Domain.Bookings.BookingRole", "Signatory")
                        .WithOne()
                        .HasForeignKey("RentFlow.Domain.Bookings.Booking", "SignatoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("RentFlow.Domain.Bookings.BookingAssetSnapshot", "AssetSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CanDeliver")
                                .HasColumnType("boolean");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<decimal>("DailyPrice")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("DeliveryPrice")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Deposit")
                                .HasColumnType("numeric");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("RentFlow.Domain.Bookings.RentalPeriod", "RentalPeriod", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartDate");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("RentFlow.Domain.Bookings.Snapshots.BookingCustomerSnapshot", "CustomerSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("FactAddress")
                                .HasColumnType("text");

                            b1.Property<string>("KPP")
                                .HasColumnType("text");

                            b1.Property<string>("OrganizationAddress")
                                .HasColumnType("text");

                            b1.Property<string>("OrganizationName")
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<string>("ShortName")
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("RentFlow.Domain.Customers.BankAccount", "BankAccount", b2 =>
                                {
                                    b2.Property<Guid>("BookingCustomerSnapshotBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("BIK")
                                        .HasColumnType("text");

                                    b2.Property<string>("BankName")
                                        .HasColumnType("text");

                                    b2.Property<string>("CorrespondentAccount")
                                        .HasColumnType("text");

                                    b2.Property<string>("CurrentAccount")
                                        .HasColumnType("text");

                                    b2.HasKey("BookingCustomerSnapshotBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingCustomerSnapshotBookingId");
                                });

                            b1.OwnsOne("RentFlow.Domain.Customers.PersonName", "Name", b2 =>
                                {
                                    b2.Property<Guid>("BookingCustomerSnapshotBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("text");

                                    b2.HasKey("BookingCustomerSnapshotBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingCustomerSnapshotBookingId");
                                });

                            b1.OwnsOne("RentFlow.Domain.Customers.Passport", "Passport", b2 =>
                                {
                                    b2.Property<Guid>("BookingCustomerSnapshotBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("IssuedBy")
                                        .HasColumnType("text");

                                    b2.Property<DateOnly?>("IssuedDate")
                                        .HasColumnType("date");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("RegistrationAddress")
                                        .HasColumnType("text");

                                    b2.Property<string>("Serial")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("BookingCustomerSnapshotBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("BookingCustomerSnapshotBookingId");
                                });

                            b1.Navigation("BankAccount");

                            b1.Navigation("Name");

                            b1.Navigation("Passport");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.Driver", "BookingDriver", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("RentFlow.Domain.Customers.DriverLicense", "License", b2 =>
                                {
                                    b2.Property<Guid>("DriverBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Categories")
                                        .HasColumnType("text");

                                    b2.Property<DateOnly?>("ExpirationDate")
                                        .HasColumnType("date");

                                    b2.Property<DateOnly?>("IssuedDate")
                                        .HasColumnType("date");

                                    b2.Property<string>("Number")
                                        .HasColumnType("text");

                                    b2.HasKey("DriverBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("DriverBookingId");
                                });

                            b1.OwnsOne("RentFlow.Domain.Customers.PersonName", "Name", b2 =>
                                {
                                    b2.Property<Guid>("DriverBookingId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FirstName")
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .HasColumnType("text");

                                    b2.Property<string>("MiddleName")
                                        .HasColumnType("text");

                                    b2.HasKey("DriverBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("DriverBookingId");
                                });

                            b1.Navigation("License")
                                .IsRequired();

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.Navigation("AssetSnapshot")
                        .IsRequired();

                    b.Navigation("BookingDriver")
                        .IsRequired();

                    b.Navigation("CustomerSnapshot")
                        .IsRequired();

                    b.Navigation("RentalPeriod")
                        .IsRequired();

                    b.Navigation("Signatory");
                });

            modelBuilder.Entity("RentFlow.Domain.Bookings.BookingRole", b =>
                {
                    b.HasOne("RentFlow.Domain.Bookings.Booking", null)
                        .WithMany("Roles")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.Individual", b =>
                {
                    b.OwnsOne("RentFlow.Domain.Customers.BankAccount", "IndividualBankAccount", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BIK")
                                .HasColumnType("text");

                            b1.Property<string>("BankName")
                                .HasColumnType("text");

                            b1.Property<string>("CorrespondentAccount")
                                .HasColumnType("text");

                            b1.Property<string>("CurrentAccount")
                                .HasColumnType("text");

                            b1.HasKey("IndividualId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.DriverLicense", "IndividualDriverLicense", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<char>>("Categories")
                                .IsRequired()
                                .HasColumnType("character(1)[]");

                            b1.Property<DateOnly?>("ExpirationDate")
                                .HasColumnType("date");

                            b1.Property<DateOnly?>("IssuedDate")
                                .HasColumnType("date");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IndividualId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.Passport", "IndividualPassport", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("uuid");

                            b1.Property<string>("IssuedBy")
                                .HasColumnType("text");

                            b1.Property<DateOnly?>("IssuedDate")
                                .HasColumnType("date");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RegistrationAddress")
                                .HasColumnType("text");

                            b1.Property<string>("Serial")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IndividualId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text");

                            b1.Property<string>("MiddleName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text");

                            b1.HasKey("IndividualId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.Navigation("IndividualBankAccount");

                    b.Navigation("IndividualDriverLicense");

                    b.Navigation("IndividualPassport");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.IndividualEntrepreneur", b =>
                {
                    b.OwnsOne("RentFlow.Domain.Customers.DriverLicense", "EntrepreneurDriverLicense", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntrepreneurId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<char>>("Categories")
                                .IsRequired()
                                .HasColumnType("character(1)[]");

                            b1.Property<DateOnly?>("ExpirationDate")
                                .HasColumnType("date");

                            b1.Property<DateOnly?>("IssuedDate")
                                .HasColumnType("date");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IndividualEntrepreneurId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.BankAccount", "IPBankAccount", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntrepreneurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BIK")
                                .HasColumnType("text");

                            b1.Property<string>("BankName")
                                .HasColumnType("text");

                            b1.Property<string>("CorrespondentAccount")
                                .HasColumnType("text");

                            b1.Property<string>("CurrentAccount")
                                .HasColumnType("text");

                            b1.HasKey("IndividualEntrepreneurId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.Passport", "IPPassport", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntrepreneurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("IssuedBy")
                                .HasColumnType("text");

                            b1.Property<DateOnly?>("IssuedDate")
                                .HasColumnType("date");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RegistrationAddress")
                                .HasColumnType("text");

                            b1.Property<string>("Serial")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IndividualEntrepreneurId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.ValueObjects.OrganizationLegalForm", "IpLegalForm", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntrepreneurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("LegalFormFullName");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("LegalFormShortName");

                            b1.HasKey("IndividualEntrepreneurId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("IndividualEntrepreneurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text");

                            b1.Property<string>("MiddleName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text");

                            b1.HasKey("IndividualEntrepreneurId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("IndividualEntrepreneurId");
                        });

                    b.Navigation("EntrepreneurDriverLicense");

                    b.Navigation("IPBankAccount")
                        .IsRequired();

                    b.Navigation("IPPassport")
                        .IsRequired();

                    b.Navigation("IpLegalForm")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("RentFlow.Domain.Customers.Organization", b =>
                {
                    b.OwnsOne("RentFlow.Domain.Customers.ValueObjects.OrganizationLegalForm", "LegalForm", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("LegalFormFullName");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("text")
                                .HasColumnName("LegalFormShortName");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.BankAccount", "OrganizationBankAccount", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BIK")
                                .HasColumnType("text");

                            b1.Property<string>("BankName")
                                .HasColumnType("text");

                            b1.Property<string>("CorrespondentAccount")
                                .HasColumnType("text");

                            b1.Property<string>("CurrentAccount")
                                .HasColumnType("text");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("RentFlow.Domain.Customers.SigningBasis", "SigningBasis", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("AttorneyDate")
                                .HasColumnType("date");

                            b1.Property<string>("AttorneyNumber")
                                .HasColumnType("text");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("LegalForm")
                        .IsRequired();

                    b.Navigation("OrganizationBankAccount")
                        .IsRequired();

                    b.Navigation("SigningBasis")
                        .IsRequired();
                });

            modelBuilder.Entity("RentFlow.Domain.Assets.Asset", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("RentFlow.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
